name: 'Test action code'
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test git signature verification action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          make test
